apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  SERVICE: {{ .Chart.Name }}
  VERSION: {{ .Chart.Version }}

  PORT: {{ .Values.port | quote}}
  NODE_ENV: "production"