apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/auth-url: https://auth.mobilityservices.io
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/configuration-snippet: |
        access_log /dev/stdout log_with_request_body;
spec:
  tls:
    - hosts:
        - {{ .Values.service }}.{{ .Release.Namespace }}.{{ .Values.global.base_url }}
      secretName: {{ .Values.service }}.{{ .Release.Namespace }}.{{ .Values.global.base_url }}
  rules:
    - host: {{ .Values.service }}.{{ .Release.Namespace }}.{{ .Values.global.base_url }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
              servicePort: {{ .Values.port }}
